export default {
  UPDATE_EXPERIENCE_DETAIL: 'UPDATE_EXPERIENCE_DETAIL',
  UPDATE_EXPERIENCE_DETAIL_COUNT: 'UPDATE_EXPERIENCE_DETAIL_COUNT',
  DELETE_EXPERIENCE_DETAIL_COUNT: 'DELETE_EXPERIENCE_DETAIL_COUNT'
}
